DROP DATABASE IF EXISTS quanlybenhnhan;
CREATE DATABASE quanlybenhnhan CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE quanlybenhnhan;

CREATE TABLE Khoa (
    MaKhoa VARCHAR(10) PRIMARY KEY,
    TenKhoa VARCHAR(100) NOT NULL
);

CREATE TABLE ChucVu (
    MaCV VARCHAR(10) PRIMARY KEY,
    TenCV VARCHAR(100) NOT NULL
);

CREATE TABLE BenhNhan (
    MaBN VARCHAR(10) PRIMARY KEY,
    HoBN VARCHAR(50),
    TenBN VARCHAR(50),
    GioiTinh VARCHAR(10),
    TuoiBN INT,
    SDTBN VARCHAR(15),
    NgaySinh DATE,
    DiaChi VARCHAR(100)
);

CREATE TABLE BHYT (
    MaBHYT VARCHAR(20) PRIMARY KEY,
    NgayBDBHYT DATE,
    NgayHHBHYT DATE,
    QueQuan VARCHAR(100)
);

CREATE TABLE MacBenh (
    MaBenh VARCHAR(10) PRIMARY KEY,
    LoaiBenh VARCHAR(50),
    MaBN VARCHAR(10),
    FOREIGN KEY (MaBN) REFERENCES BenhNhan(MaBN)
);

CREATE TABLE NhanVien (
    MaNV VARCHAR(10) PRIMARY KEY,
    HoTenNV VARCHAR(100),
    TuoiNV INT,
    GioiTinhNV VARCHAR(10),
    SDTNV VARCHAR(15),
    MaKhoa VARCHAR(10),
    MaCV VARCHAR(10),
    FOREIGN KEY (MaKhoa) REFERENCES Khoa(MaKhoa),
    FOREIGN KEY (MaCV) REFERENCES ChucVu(MaCV)
);

CREATE TABLE DieuTri (
    NgayBDDieuTri DATE NOT NULL,
    NgayXuatVien DATE,
    MaBN VARCHAR(10),
    MaNV VARCHAR(10),
    PRIMARY KEY (NgayBDDieuTri, MaBN, MaNV),
    FOREIGN KEY (MaBN) REFERENCES BenhNhan(MaBN),
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

CREATE TABLE Thuoc (
    MaThuoc VARCHAR(10) PRIMARY KEY,
    TenThuoc VARCHAR(100)
);

CREATE TABLE DonThuoc (
    MaDT VARCHAR(10) PRIMARY KEY,
    TenDT VARCHAR(100),
    CachSuDung VARCHAR(200),
    DonViTinh VARCHAR(50)
);

